Repository mohanadarafe/GuideMe, pull requests merged in 2020-04, with the labels that each got.

#191 Implementation of the Side Navigation Menu
  App.js
  __tests__/unit/AboutUs.test.js
  __tests__/unit/CourseSchedule.test.js
  __tests__/unit/CourseScheduleDetails.test.js
  __tests__/unit/MoreDetails.test.js
  __tests__/unit/NearbyInterest.test.js
  __tests__/unit/NearbyInterestDetails.test.js
  __tests__/unit/Settings.test.js
  assets/Concordia_Darken.png
  assets/separator_line.png
  components/BottomMenu.js
  components/Search.js
  package-lock.json
  package.json
  routes/aboutUsStack.js
  routes/drawer.js
  routes/nearbyInterestStack.js
  routes/routeStack.js
  routes/scheduleStack.js
  routes/settingsStack.js
  routes/shuttleBusStack.js
  screens/Map.js
  screens/Menu/AboutUs.js
  screens/Menu/CourseSchedule.js
  screens/Menu/CourseScheduleDetails.js
  screens/Menu/NearbyInterest.js
  screens/Menu/NearbyInterestDetails.js
  screens/Menu/Settings.js
  screens/Menu/ShuttleBus.js
  screens/MoreDetails.js
  screens/Nearby.js
  screens/PreferenceMenu.js
  screens/SideMenu.js
Labels: pull request

#198 Add arrow for direction to follow in indoor map
  components/IndoorDirections/Dijkstra/DijkstraAlgorithm.js
  components/IndoorDirections/TypesOfDirections/DifferentBuildingDirections.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  constants/HallXCoordinates.js
Labels: pull request

#209 JMSB to MB Building Bug fixed.
  __tests__/unit/DoubleSearch.test.js
  __tests__/unit/MoreDetails.test.js
  components/BuildingHighlight.js
  components/FloorMenu.js
  constants/buildingCoordinates.js
  constants/buildingData.js
  screens/Indoor/IndoorMapView.js
Labels: bug, enhancement

#212 Enhancement: UI fixes for the Side Menu screens
  components/BottomMenu.js
  components/Search.js
  routes/drawer.js
  routes/nearbyInterestStack.js
  screens/DoubleSearch.js
  screens/Menu/AboutUs.js
  screens/Menu/CourseSchedule.js
  screens/Menu/CourseScheduleDetails.js
  screens/Menu/NearbyInterest.js
  screens/Menu/NearbyInterestDetails.js
  screens/Menu/Settings.js
  screens/Menu/ShuttleBus.js
  screens/SideMenu.js
Labels: bug, enhancement

#213 Search bar is now connected to BottomMenu and MoreDetails
  __tests__/unit/MoreDetails.test.js
  __tests__/unit/Search.test.js
  app.json
  components/BottomMenu.js
  components/CurrentBuildingLocation.js
  components/IndoorDirections/TypesOfDirections/DifferentBuildingDirections.js
  components/MapData.js
  components/Search.js
  constants/buildingData.js
  package-lock.json
  package.json
  screens/DoubleSearch.js
  screens/MoreDetails.js
Labels: bug, implementation, pull request

#216 US30 - As a user, I would like to be able to highlight points of interest such as washrooms, water foundations etc.
  __tests__/unit/Directions/DifferentBuildingDirections.test.js
  __tests__/unit/Directions/DifferentFloorDirections.test.js
  __tests__/unit/Directions/SameFloorDIrections.test.js
  __tests__/unit/Directions/__snapshots__/DifferentBuildingDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/DifferentFloorDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/SameFloorDIrections.test.js.snap
  __tests__/unit/HallFloor9.test.js
  __tests__/unit/HallFloorX.test.js
  assets/floormaps/hall/HallFloor9.js
  assets/floormaps/hall/HallFloorX.js
  components/IndoorDirections/Dijkstra/DijkstraAlgorithm.js
  components/IndoorDirections/IndoorScenario.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  constants/ClassGraph.js
  constants/ClassGraph9.js
  constants/ClassRooms.js
  constants/Hall9Coordinates.js
  constants/HallXCoordinates.js
  package-lock.json
  package.json
  screens/DoubleSearch.js
Labels: pull request

#222 increase test coverage to 77% + fix all console warning issues for indoor maps
  __tests__/unit/Directions/DifferentBuildingDirections.test.js
  __tests__/unit/Directions/DifferentFloorDirections.test.js
  __tests__/unit/Directions/SameFloorDIrections.test.js
  __tests__/unit/Directions/__snapshots__/DifferentBuildingDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/DifferentFloorDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/IndoorScenario.test.js.snap
  __tests__/unit/Directions/__snapshots__/SameFloorDIrections.test.js.snap
  __tests__/unit/VLFloor1.test.js
  assets/floormaps/hall/HallFloor9.js
  assets/floormaps/hall/HallFloorX.js
  components/IndoorDirections/TypesOfDirections/DifferentBuildingDirections.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  package.json
Labels: pull request

#223 US29 - As a user, I would like to show paths optimized for access by students with disabilities + Initial Floor in Indoor Maps selected
  __tests__/unit/Directions/IndoorScenario.test.js
  __tests__/unit/Directions/__snapshots__/DifferentFloorDirections.test.js.snap
  assets/floormaps/hall/HallFloor9.js
  assets/floormaps/hall/HallFloorX.js
  assets/floormaps/vl/VLFloor1.js
  components/BottomMenu.js
  components/FloorMenu.js
  components/IndoorDirections/Dijkstra/DijkstraAlgorithm.js
  components/IndoorDirections/IndoorScenario.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  constants/ClassGraph.js
  constants/ClassRooms.js
  package.json
  screens/Indoor/IndoorMapView.js
  screens/PreferenceMenu.js
Labels: pull request

#225 US21 - As a user, I would like to view the Concordia shuttle bus schedule for both campuses.
  __tests__/unit/ShuttleBus.test.js
  assets/ShuttleBusSVG.js
  assets/shuttle.jpg
  constants/ClassRooms.js
  constants/shuttleBustimes.js
  package-lock.json
  package.json
  routes/routeStack.js
  screens/Menu/ShuttleBus.js
Labels: pull request

#226 Outdoor Points of Interest (restaurants) #12
  __tests__/unit/CourseScheduleDetails.test.js
  __tests__/unit/Directions/__snapshots__/DifferentFloorDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/IndoorScenario.test.js.snap
  __tests__/unit/Directions/__snapshots__/SameFloorDIrections.test.js.snap
  __tests__/unit/NearbyInterest.test.js
  __tests__/unit/NearbyInterestDetails.test.js
  assets/styling/sideMenuStyling.js
  components/BottomMenu.js
  constants/constantStack.js
  package-lock.json
  package.json
  routes/nearbyInterestStack.js
  routes/scheduleStack.js
  screens/Directions.js
  screens/DoubleSearch.js
  screens/Menu/AboutUs.js
  screens/Menu/CourseSchedule.js
  screens/Menu/CourseScheduleDetails.js
  screens/Menu/NearbyInterest.js
  screens/Menu/NearbyInterestDetails.js
  screens/Menu/Settings.js
  screens/Menu/ShuttleBus.js
  screens/PreviewDirections.js
Labels: pull request

#228 Consolidation of bugs/Features & Redux implementation
  App.js
  __tests__/system/BottomMenu.test.js
  __tests__/system/Map.test.js
  __tests__/unit/BuildingHighlight.test.js
  __tests__/unit/Directions/__snapshots__/IndoorScenario.test.js.snap
  __tests__/unit/NearbyInterest.test.js
  __tests__/unit/PreferenceMenu.test.js
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/CurrentBuildingLocation.js
  components/CurrentLocationButton.js
  components/Search.js
  components/locationMarker.js
  constants/buildingCoordinates.js
  constants/buildingData.js
  package-lock.json
  package.json
  redux/reducers/index.js
  screens/Directions.js
  screens/DoubleSearch.js
  screens/Map.js
  screens/Menu/CourseSchedule.js
  screens/Menu/NearbyInterest.js
  screens/PreferenceMenu.js
  screens/PreviewDirections.js
Labels: pull request

#242 Reduce Code Duplication + Refactoring
  .gitignore
  __tests__/unit/Components/CurrentBuildingLocation.test.js
  __tests__/unit/Components/CurrentLocationButton.test.js
  __tests__/unit/Components/FloorMenu.test.js
  __tests__/unit/Components/Search.test.js
  __tests__/unit/Screens/PreferenceMenu/PreferenceMenu.test.js
  __tests__/unit/Screens/SideMenu/AboutUs.test.js
  __tests__/unit/Screens/SideMenu/CourseSchedule.test.js
  __tests__/unit/Screens/SideMenu/NearbyInterest.test.js
  __tests__/unit/Screens/SideMenu/NearbyInterestDetails.test.js
  __tests__/unit/Screens/SideMenu/Settings.test.js
  assets/styling/mapDarkMode.js
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/CurrentBuildingLocation.js
  components/CurrentLocationButton.js
  components/FloorMenu.js
  components/IndoorDirections/Dijkstra/DijkstraAlgorithm.js
  components/IndoorDirections/IndoorScenario.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  components/MapData.js
  components/Search.js
  components/locationMarker.js
  constants/ClassGraph.js
  constants/ClassGraph9.js
  constants/ClassRooms.js
  constants/Hall9Coordinates.js
  constants/HallXCoordinates.js
  constants/LoyolaCoordinates.js
  constants/LoyolaGraph.js
  constants/buildingCoordinates.js
  constants/buildingData.js
  constants/constantStack.js
  constants/shuttleBustimes.js
  redux/reducers/index.js
  routes/aboutUsStack.js
  routes/nearbyInterestStack.js
  routes/scheduleStack.js
  routes/settingsStack.js
  screens/Directions.js
  screens/DoubleSearch.js
  screens/Indoor/IndoorMapView.js
  screens/Map.js
  screens/Menu/AboutUs.js
  screens/Menu/CourseSchedule.js
  screens/Menu/NearbyInterest.js
  screens/Menu/NearbyInterestDetails.js
  screens/Menu/Settings.js
  screens/Menu/ShuttleBus.js
  screens/MoreDetails.js
  screens/PreferenceMenu.js
  screens/PreviewDirections.js
  screens/SideMenu.js
Labels: SonarQube, pull request, refactoring

#241 System Testing - Sprint 2 US covered and tested
  components/BottomMenu.js
  components/FloorMenu.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  e2e/CompositeDirectionsTest.spec.js
  e2e/ExplorationTest.spec.js
  e2e/IndoorDirectionsTest.spec.js
  e2e/OutdoorDirectionsTest.spec.js
  e2e/systemTest.spec.js
  package-lock.json
  package.json
  screens/Directions.js
  screens/DoubleSearch.js
  screens/Indoor/IndoorMapView.js
  screens/Map.js
  screens/Menu/NearbyInterest.js
  screens/MoreDetails.js
  screens/PreferenceMenu.js
  screens/PreviewDirections.js
  screens/SideMenu.js
Labels: System Test, testing

#243 E2e automated testing sprint3 & 4
  components/BottomMenu.js
  components/Search.js
  constants/HallXCoordinates.js
  e2e/CompositeDirectionsTest.spec.js
  e2e/IndoorDirectionsTest.spec.js
  e2e/OutdoorDirectionsTest.spec.js
  e2e/SideMenu.spec.js
  e2e/init.js
  routes/drawer.js
  screens/Directions.js
  screens/Menu/NearbyInterest.js
  screens/MoreDetails.js
  screens/PreviewDirections.js
Labels: System Test, testing
