Repository mohanadarafe/GuideMe, pull requests merged in 2020-03, with the labels that each got.

#117 Fix all eslint errors in the code.
  components/AccessibilityIdentification.js
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/BuildingIdentification.js
  components/CurrentLocation.js
  components/MapData.js
  components/Search.js
  constants/buildingCoordinates.js
  constants/sgwRooms.js
  routes/routeStack.js
  screens/Map.js
  screens/MoreDetails.js
  utils/Index.js
Labels: enhancement

#126 US37 - As a user, I would like to navigate through building floors. #59
  assets/floormaps/hall/HallClassrooms/HallClass.js
  assets/floormaps/hall/HallFloor9.js
  assets/floormaps/hall/HallFloorX.js
  assets/floormaps/mb/JMSBFloor1.js
  assets/floormaps/mb/JMSBFloor2.js
  assets/floormaps/mb/JMSBFloorX.js
  components/BottomMenu.js
  components/FloorMenu.js
  package-lock.json
  package.json
  screens/Indoor/IndoorMapView.js
  screens/Map.js
Labels: epic_5, user story

#134 Feature/preferences: Add DoubleSearch screen, PreferenceMenu page, layout of the Directions screen.
  .gitignore
  App.js
  __tests__/system/Map.test.js
  __tests__/system/MoreDetails.test.js
  __tests__/unit/AccesibilityIdentification.test.js
  __tests__/unit/BuildingHighlight.test.js
  __tests__/unit/BuildingIdentification.test.js
  __tests__/unit/CurrentLocation.test.js
  __tests__/unit/MapData.test.js
  __tests__/unit/Search.test.js
  app.json
  assets/DoubleSearchSVG.js
  assets/floormaps/hall/HallClassrooms/HallClass.js
  assets/floormaps/hall/HallFloor9.js
  assets/floormaps/hall/HallFloorX.js
  assets/floormaps/mb/JMSBFloor1.js
  assets/floormaps/mb/JMSBFloor2.js
  assets/floormaps/mb/JMSBFloorX.js
  babel.config.js
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/Directions.js
  components/PreferenceMenu.js
  components/Search.js
  package-lock.json
  package.json
  react-native.config.js
  routes/routeStack.js
  screens/DoubleSearch.js
  screens/Indoor/IndoorMapView.js
  screens/Map.js
  screens/MoreDetails.js
  setupTests.js
Labels: pull request

#137 US31 - As a user, I would like to be able to generate directions to rooms between floors. #40
  __tests__/unit/BuildingIdentification.test.js
  __tests__/unit/CurrentLocation.test.js
  __tests__/unit/Directions/DifferentBuildingDirections.test.js
  __tests__/unit/Directions/DifferentFloorDirections.test.js
  __tests__/unit/Directions/IndoorScenario.test.js
  __tests__/unit/Directions/SameFloorDIrections.test.js
  __tests__/unit/Directions/__snapshots__/DifferentBuildingDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/DifferentFloorDirections.test.js.snap
  __tests__/unit/Directions/__snapshots__/IndoorScenario.test.js.snap
  __tests__/unit/Directions/__snapshots__/SameFloorDIrections.test.js.snap
  __tests__/unit/HallFloor9.test.js
  __tests__/unit/HallFloorX.test.js
  __tests__/unit/JMSBFloor1.test.js
  __tests__/unit/JMSBFloor2.test.js
  __tests__/unit/JMSBFloorX.test.js
  __tests__/unit/PreferenceMenu.test.js
  assets/floormaps/hall/HallFloorX.js
  components/BottomMenu.js
  components/FloorMenu.js
  components/IndoorDirections/Dijkstra/DijkstraAlgorithm.js
  components/IndoorDirections/IndoorScenario.js
  components/IndoorDirections/TypesOfDirections/DifferentBuildingDirections.js
  components/IndoorDirections/TypesOfDirections/DifferentFloorDirections.js
  components/IndoorDirections/TypesOfDirections/SameFloorDirections.js
  components/PreferenceMenu.js
  components/Search.js
  constants/ClassGraph.js
  constants/HallXCoordinates.js
  constants/sgwRooms.js
  package.json
  screens/DoubleSearch.js
Labels: pull request, user story

#128 Feature/icon for displaying current location
  __tests__/unit/CurrentBuildingLocation.test.js
  __tests__/unit/CurrentLocation.test.js
  components/BottomMenu.js
  components/CurrentBuildingLocation.js
  components/Directions.js
  package-lock.json
  package.json
  screens/Map.js
Labels: pull request

#141 Added coordinates to buildingData
  constants/buildingData.js
Labels: enhancement

#143 Get the unit tests at at least 70% coverage
  __tests__/system/BottomMenu.test.js
  __tests__/unit/BuildingHighlight.test.js
  __tests__/unit/Directions/DifferentBuildingDirections.test.js
  __tests__/unit/Directions/IndoorScenario.test.js
  __tests__/unit/Directions/__snapshots__/IndoorScenario.test.js.snap
  __tests__/unit/DoubleSearchSVG.test.js
  __tests__/unit/FloorMenu.test.js
  __tests__/unit/HallClass.test.js
  __tests__/unit/IndoorMapView.test.js
  __tests__/unit/MoreDetails.test.js
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/FloorMenu.js
  screens/DoubleSearch.js
  screens/MoreDetails.js
Labels: pull request, testing

#148 Bug/cutoff labels in bottom menu
  components/BottomMenu.js
Labels: enhancement

#165 Feature/detox setup
  .gitignore
  components/BottomMenu.js
  components/Search.js
  detox-setup.sh
  e2e/config.json
  e2e/firstTest.spec.js
  e2e/init.js
  package-lock.json
  package.json
  screens/Map.js
Labels: enhancement, pull request, testing

#171 Outdoor direction implementation with Google Maps API
  .gitignore
  App.js
  __tests__/system/MoreDetails.test.js
  __tests__/unit/CurrentLocationButton.test.js
  __tests__/unit/IndoorMapView.test.js
  __tests__/unit/MoreDetails.test.js
  __tests__/unit/Nearby.test.js
  __tests__/unit/PreferenceMenu.test.js
  babel.config.js
  components/BottomMenu.js
  components/CurrentBuildingLocation.js
  components/CurrentLocationButton.js
  components/Directions.js
  database.config.js
  package-lock.json
  package.json
  routes/routeStack.js
  screens/Directions.js
  screens/DoubleSearch.js
  screens/Indoor/IndoorMapView.js
  screens/Map.js
  screens/MoreDetails.js
  screens/Nearby.js
  screens/PreferenceMenu.js
  screens/PreviewDirections.js
  services/getApiKey.js
Labels: pull request

#184 feat: add logo to splash screen (#120)
  app.json
  assets/splash.png
Labels: pull request

#186 Automated End 2 End Testing
  components/BottomMenu.js
  components/BuildingHighlight.js
  components/FloorMenu.js
  e2e/firstTest.spec.js
  e2e/systemTest.spec.js
  package-lock.json
  package.json
  screens/DoubleSearch.js
  screens/Indoor/IndoorMapView.js
  screens/Map.js
  screens/MoreDetails.js
Labels: System Test, testing
